# Generated by Django 6.1 on 2026-09-03 00:02

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('infosite_project_id', models.PositiveIntegerField(blank=True, help_text='Linked InfoSiteProject.id (canonical data source origin).', null=True)),
                ('editorial_notes', wagtail.fields.RichTextField(blank=True, help_text='Curation/review notes for this data source.')),
            ],
            options={
                'verbose_name': 'Data Source Detail Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DataSourceIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Editorial introduction shown above the data source catalog.')),
            ],
            options={
                'verbose_name': 'Data Source Catalog Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
