# Generated by Django 6.1 on 2026-09-03 08:02

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_cms', '0001_initial'),
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBlockDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('infosite_project_id', models.PositiveIntegerField(blank=True, help_text='Linked InfoSiteProject.id whose extracted knowledge blocks are shown here.', null=True)),
                ('editorial_notes', wagtail.fields.RichTextField(blank=True, help_text='Curation/review notes for this block set.')),
            ],
            options={
                'verbose_name': 'Knowledge Block Detail Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='KnowledgeBlockIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Editorial introduction shown above the knowledge-block catalog.')),
            ],
            options={
                'verbose_name': 'Knowledge Block Catalog Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
