# Generated by Django 6.1 on 2026-09-02 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoSiteProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display title for the knowledge base', max_length=255)),
                ('domain', models.CharField(default='default', help_text='Domain/namespace for content', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of this knowledge base')),
                ('source_directory', models.CharField(blank=True, help_text='Path to source documents directory', max_length=500)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_generated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Infosite Project',
                'verbose_name_plural': 'Infosite Projects',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Path to the document file', max_length=500)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('markdown', 'Markdown'), ('text', 'Text'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('imported', models.BooleanField(default=False)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='django_site.infositeproject')),
            ],
            options={
                'verbose_name': 'Source Document',
                'verbose_name_plural': 'Source Documents',
                'ordering': ['file_path'],
                'unique_together': {('project', 'file_path')},
            },
        ),
    ]
