# Generated by Django 6.1 on 2026-09-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infositeproject',
            name='auto_discover',
            field=models.BooleanField(default=True, help_text='Automatically discover documents from source directory'),
        ),
        migrations.AddField(
            model_name='infositeproject',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last document discovery/sync', null=True),
        ),
        migrations.AddField(
            model_name='infositeproject',
            name='last_sync_error',
            field=models.TextField(blank=True, help_text='Error message from last failed sync'),
        ),
        migrations.AddField(
            model_name='infositeproject',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of the last document sync', max_length=20),
        ),
        migrations.AddField(
            model_name='infositeproject',
            name='working_title',
            field=models.CharField(blank=True, help_text='Working title/project code (used in discovery: md/<domain>/<working_title>)', max_length=100),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='file_size',
            field=models.IntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='import_error',
            field=models.TextField(blank=True, help_text='Error message from last failed import'),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='import_status',
            field=models.CharField(choices=[('discovered', 'Discovered'), ('pending', 'Pending Import'), ('imported', 'Imported'), ('failed', 'Failed')], default='discovered', help_text='Current import status', max_length=20),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='modified_at',
            field=models.DateTimeField(blank=True, help_text='File modification time', null=True),
        ),
    ]
