# Generated by Django 6.1 on 2026-09-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site', '0002_infositeproject_auto_discover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infositeproject',
            name='generated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful generation', null=True),
        ),
        migrations.AddField(
            model_name='infositeproject',
            name='generation_error',
            field=models.TextField(blank=True, help_text='Error message from last failed generation'),
        ),
        migrations.AddField(
            model_name='infositeproject',
            name='generation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of the last generation attempt', max_length=20),
        ),
        migrations.AddField(
            model_name='infositeproject',
            name='output_dir',
            field=models.CharField(blank=True, help_text='Path to generated output directory', max_length=500),
        ),
        migrations.AddField(
            model_name='infositeproject',
            name='version_count',
            field=models.IntegerField(default=0, help_text='Number of versions in _originals/ directory'),
        ),
    ]
