# Generated by Django 6.1 on 2026-09-03 09:38

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site', '0004_sourcedocument_editor_notes_sourcedocument_expire_at_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('file_path', models.CharField(help_text='Path to the generated file under data_out/.', max_length=500)),
                ('generated_at', models.DateTimeField(auto_now=True, help_text='Last time this file was (re-)generated/refined.')),
                ('ai_refinement_mode', models.CharField(blank=True, choices=[('', 'Keine Verfeinerung (Rohausgabe)'), ('improve', 'Improve'), ('structure', 'Restructure'), ('summarize', 'Summarize'), ('all', 'All')], default='', max_length=20)),
                ('content_hash', models.CharField(blank=True, help_text='Short hash of the file content, for change detection.', max_length=64)),
                ('review_status', models.CharField(choices=[('none', 'Nicht bewertet'), ('in_review', 'In Prüfung'), ('approved', 'Freigegeben'), ('rejected', 'Abgelehnt')], default='none', help_text='Editorial review/approval status for this output file.', max_length=20)),
                ('editor_notes', models.TextField(blank=True, help_text='Freitext-Notizen der Redaktion zu dieser Ausgabedatei.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='django_site.infositeproject')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('used_sources', models.ManyToManyField(blank=True, related_name='used_in_generated_documents', to='django_site.sourcedocument')),
            ],
            options={
                'verbose_name': 'Generated Document',
                'verbose_name_plural': 'Generated Documents',
                'ordering': ['file_path'],
                'unique_together': {('project', 'file_path')},
            },
        ),
    ]
