# Generated by Django 6.1 on 2026-09-07 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site', '0008_editorial_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80)),
                ('title', models.CharField(default='Dashboard', max_length=120)),
                ('area_key', models.CharField(choices=[('datasources', 'Data Sources'), ('knowledge', 'Knowledge'), ('infooutput', 'Info Output'), ('admin', 'Admin'), ('settings', 'Settings')], default='settings', max_length=40)),
                ('layout_mode', models.CharField(default='grid', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='django_site.domain')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['domain__slug', 'area_key', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidgetPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_id', models.CharField(max_length=200)),
                ('title_override', models.CharField(blank=True, max_length=200)),
                ('x', models.PositiveIntegerField(default=0)),
                ('y', models.PositiveIntegerField(default=0)),
                ('w', models.PositiveIntegerField(default=6)),
                ('h', models.PositiveIntegerField(default=1)),
                ('sort_index', models.PositiveIntegerField(default=0)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='django_site.dashboarddefinition')),
            ],
            options={
                'ordering': ['dashboard', 'sort_index', 'widget_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='dashboarddefinition',
            constraint=models.UniqueConstraint(fields=('owner', 'domain', 'area_key', 'slug'), name='uniq_dashboard_owner_domain_area_slug'),
        ),
        migrations.AddConstraint(
            model_name='dashboardwidgetplacement',
            constraint=models.UniqueConstraint(fields=('dashboard', 'widget_id'), name='uniq_dashboard_widget_id'),
        ),
    ]
