# Generated by Django 6.1 on 2026-09-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site', '0009_dashboarddefinition_dashboardwidgetplacement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infositeproject',
            name='site_structure',
            field=models.JSONField(blank=True, default=dict, help_text='Preferred ordering of top-level sections for the generated infosite. Can be a list of section titles or a nested tree structure.'),
        ),
        migrations.AlterField(
            model_name='dashboarddefinition',
            name='area_key',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('datasources', 'Data Sources'), ('knowledge', 'Knowledge'), ('infooutput', 'Info Output'), ('admin', 'Admin'), ('settings', 'Settings')], default='settings', max_length=40),
        ),
    ]
