# Generated by Django 6.1 on 2026-09-08 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site', '0010_infositeproject_site_structure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoSiteMappingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(blank=True, help_text='Relative source path, e.g. anthro/sstk/10_geistige_welt/anspruch-und-ziel.md', max_length=500)),
                ('target_parent', models.CharField(blank=True, help_text='Parent section slug, e.g. 10_geistige_welt', max_length=200)),
                ('target_section', models.CharField(blank=True, help_text='Section slug or title for the generated output section', max_length=200)),
                ('target_title', models.CharField(blank=True, help_text='Optional override for the generated title', max_length=255)),
                ('target_slug', models.SlugField(blank=True, max_length=200)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('mode', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual'), ('override', 'Override')], default='manual', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_rules', to='django_site.infositeproject')),
                ('source_document', models.ForeignKey(blank=True, help_text='Source document that should be placed into the generated page tree.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_rules', to='django_site.sourcedocument')),
            ],
            options={
                'ordering': ['project', 'order_index', 'target_section', 'source_path'],
                'constraints': [models.UniqueConstraint(fields=('project', 'source_path'), name='uniq_infosite_mapping_project_source_path')],
            },
        ),
    ]
