# Generated by Django 6.1 on 2026-09-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site', '0011_infositemappingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='infositeproject',
            name='generate_html_site',
            field=models.BooleanField(default=False, help_text='Also generate a static HTML website alongside the markdown output.'),
        ),
    ]
