# Generated by Django 6.1 on 2026-09-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site', '0012_infositeproject_generate_html_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='infositeproject',
            name='html_site_generated',
            field=models.BooleanField(default=False, help_text='Whether the static HTML preview for this project was already generated successfully.'),
        ),
        migrations.AlterField(
            model_name='infositeproject',
            name='generate_html_site',
            field=models.BooleanField(default=False, help_text='Default setting: also generate a static HTML website alongside the markdown output.'),
        ),
    ]
